### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by zainsadaqat** [zainsadaqat/javascript-capstone-pokeapi#61]
### Hello!
> This is our **javascript capstone** project where initially we're setting up the **kanban board** for our project. We've already assigned the tasks. We are a group of two members. Student A is @aristides1000  and Student B is @zainsadaqat.

### Here's our project link:
https://github.com/zainsadaqat/javascript-capstone-pokeapi/projects/1

**Comment by henatan99** [comment]
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] You have provided the wrong link for the project in the issue field. I think this is the right link: [project link](https://github.com/zainsadaqat/javascript-capstone-pokeapi/projects/1). Kindly make this change and submit it for another review. 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mikenath223** [comment]
Hi there, 

Awesome job on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Let's work on those.


 ## Required Changes ♻️
_Kindly check the comments under the review._
- [ ] Please ensure that group tasks get assigned to at least one member, you could also assign a group task to both of you.


Happy coding, Cheers!🚀🚀

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Issue link submitted for the first review, whether it's valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zainsadaqat** [comment]
@mikenath223 
We have already assigned the tasks to each other. Can you please explain what are you talking about?

<img width="1289" alt="Screen Shot 2021-09-07 at 9 30 25 PM" src="https://user-images.githubusercontent.com/83048208/132380350-8c74a238-c04e-4894-b914-ed2a59750768.png">

**Comment by mikenath223** [comment]
Cool. Seems you just assigned it. Kindly request a new review then.

**Comment by mikenath223** [comment]
Hello there  

Your project is complete!  There is nothing else to say 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the issue thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
